FROM python:3.9-slim-buster
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
RUN apt-get clean && apt-get autoremove -y
CMD ["python3", "/app.py"]